test:
  adapter: mysql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: canvas
  timeout: 5000
  queue:
    adapter: mysql
    encoding: utf8
    database: canvas_queue_test
    host: localhost
    username: canvas
    timeout: 5000

test-in-memory:
  adapter: sqlite3
  encoding: utf8
  database: ':memory:'
  pool: 1

development:
  adapter: mysql
  encoding: utf8
  database: canvas_development
  host: localhost
  username: canvas
  timeout: 5000
  queue:
    adapter: mysql
    encoding: utf8
    database: canvas_queue_development
    host: localhost
    username: canvas
    timeout: 5000
    
production:
  adapter: postgresql
  encoding: utf8
  database: canvas_prod
  host: localhost
  username: canvas
  password: canvas
  timeout: 5000
  queue:
    adapter: postgresql
    encoding: utf8
    database: canvas_queue_prod
    host: localhost
    username: canvas
    password: canvas
    timeout: 5000
